version: '2'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI_DEV=mongodb://db:27017/aqua
    links:
      - db
  db:
    image: mongo
    ports:
      - "27018:27017" #Port is 27018 for the local machine
